### ISSUE TITLE
Remove horizontal padding on data section

### ISSUE THREAD

**Issue by zemetskiym** [zemetskiym/github-rest-api#4]
**Is your feature request related to a problem? Please describe.**
All elements in the main layout have no horizontal padding and take up the full width with the exception of the data section. For consistent styling, the data should take up the full width of the main layout.

**Describe the solution you'd like**
Removing any left and right padding for elements in the DataList component. The secondSection parent element should also be removed since its only purpose is to add horizontal padding.

**Describe alternatives you've considered**
I have considered adding padding to elements on the Overview and Repositories sections, but this would lead to the SectionNav being lined up incorrectly with the sections.

**Additional context**
![image](https://user-images.githubusercontent.com/122832270/220195168-71e7f7a0-5c3f-4167-a51e-4331e6bacf06.png)

**Comment by iambharathpadhu** [comment]
I can help!

**Comment by zemetskiym** [comment]
Hey @iambharathpadhu,

Thanks for offering to help. I have assigned the issue to you. Feel free to mention me if you have any questions or concerns.

**Comment by zemetskiym** [comment]
Hi @iambharathpadhu, I wanted to follow up on the issue you offered to help with and check if you have made any progress. If not, are you still planning on contributing? If you need any assistance or have any questions, please let me know. I'm happy to help in any way I can. If I don't hear back from you in the next few days, I'll assume you are no longer interested in contributing. Thank you again for your interest!

**Comment by zemetskiym** [comment]
I have pushed the commit b6a57b1 that solves this issue. The commit message is "Remove horizontal data margin for consistent style."
