### ISSUE TITLE
Add blue border to inputs on active

### ISSUE THREAD

**Issue by zemetskiym** [zemetskiym/github-rest-api#5]
**Is your feature request related to a problem? Please describe.**
In the styles/globals.css page, there are a few default styles that exist to override the default browser styles. This leads to consistency across browsers. We do not, however, have a default border to use for active inputs. 

**Describe the solution you'd like**
In the styles/globals.css page, the input tag should have a light-blue border on focus. You can do so with the :focus pseudo-class.

**Describe alternatives you've considered**
I have considered an inset box shadow on focus, but this would not fit with the current style of the page.

**Additional context**
![image](https://user-images.githubusercontent.com/122832270/220525838-c722c311-8f11-44e0-b3f2-4e4cf7f6649b.png)
A screenshot of Firefox's default focused input border is provided above.

**Comment by riungemaina** [comment]
Hello, I can help!

**Comment by predatorprasad** [comment]
Willing to work on it

**Comment by zemetskiym** [comment]
> Hello, I can help!

Hello @riungemaina,

Thanks for offering to help. I have assigned the issue to you. Feel free to mention me if you have any questions or concerns.

**Comment by zemetskiym** [comment]
Hi @riungemaina, I wanted to follow up on the issue you offered to help with and check if you have made any progress. If not, are you still planning on contributing? If you need any assistance or have any questions, please let me know. I'm happy to help in any way I can. If I don't hear back from you in the next few days, I'll assume you are no longer interested in contributing. Thank you again for your interest!

**Comment by zemetskiym** [comment]
I have pushed the commit 3da93b3 that solves this issue. The commit message is "Set default focused input border for cross-browser."

**Comment by zemetskiym** [comment]
I have pushed the commit 3da93b3 that solves this issue. The commit message is "Set default focused input border for cross-browser."
